sudo: false
language: python
python:
  - "2.7"
compiler:
  - gcc
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - nosetests -v
notifications:
 email:
   recipients:
      - github@cschwede.de
